---
title: "p8105_hw1_rr3423"
author: "Ragyie Rawal"
output: github_document
---

```{r setup, include = FALSE}
# loading packages 

library(tidyverse)
```


## PROBLEM 1 

```{r database}
# Setting seed for the random sample 

set.seed(1)

# Creating a dataframe

prob_one_df = tibble(
  random_sample = rnorm(10),
  vec_logical = c(random_sample > 0), 
  vec_character = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
  vec_factor = factor(c("low", "medium", "high", "low", "medium", "high", "low", "medium", "high", "low" ))
)

knitr::kable(prob_one_df)
```

```{r means}
# Taking the mean of each variable in the dataframe 

mean_random_sample = mean(pull(prob_one_df, random_sample))
mean_vec_logical = mean(pull(prob_one_df, vec_logical))
mean_vec_character = mean(pull(prob_one_df, vec_character))
mean_vec_factor = mean(pull(prob_one_df, vec_factor))
```

When attempting to take the mean of each variable in the dataframe, it was possible to successfully take the mean of the random sample variable and the mean of the logical vector variable. It was not possible to take the mean of the character vector variable or the mean of the factor vector variable. 

```{r converting_variables, message = FALSE, warning = FALSE}
# Applying the as.numeric function to the logical, character, and factor variables 

convert_logical = as.numeric(pull(prob_one_df, vec_logical))
convert_character = as.numeric(pull(prob_one_df, vec_logical))
convert_factor = as.numeric(pull(prob_one_df, vec_factor))
```


## PROBLEM 2 

```{r load_dataset}
# Loading the penguins data set 

data("penguins", package = "palmerpenguins")
```

